version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: "postgres://postgres:mysecretpassword@db:5432/postgres"
      REDIS_URL: "redis:6379"
    networks:
      - mynetwork

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mynetwork


networks:
  mynetwork:

volumes:
  pgdata:
